"""followers

Revision ID: 95761a8cafce
Revises: 7af845170b98
Create Date: 2022-02-24 14:54:43.776095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95761a8cafce'
down_revision = '7af845170b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
